version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0
jobs:
  setup:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: |
            npm run build
            ls dist
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  deploy:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - restore_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
      - run: ls
      - aws-s3/copy:
          arguments: --recursive
          from: dist/
          to: 's3://polyglot-spa-vue-chess'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          context: AWS S3
          requires:
            - build
          filters:
            branches:
              only: main
